#!/bin/sh
set -e

SYSLOGNG_OPTS=""

[ -r /etc/default/syslog-ng ] && . /etc/default/syslog-ng

case "x$CONSOLE_LOG_LEVEL" in
  x[1-8])
    dmesg -n $CONSOLE_LOG_LEVEL
    ;;
  x)
    ;;
  *)
    echo "CONSOLE_LOG_LEVEL is of unaccepted value."
    ;;
esac

if [ ! -e /dev/xconsole ]
then
  mknod -m 640 /dev/xconsole p
fi

if [ -n "$SYSLOG_DEST" ]; then
    if [ "$SYSLOG_DEST" != "remote" ]; then
        REMOTE_HOST="${SYSLOG_DEST%:*}"
        REMOTE_PORT="${SYSLOG_DEST##*:}"
    fi
    echo "destination d_messages { udp(\"${REMOTE_HOST:-172.17.42.1}\" port(${REMOTE_PORT:-514})); };" > \
        /etc/syslog-ng/destination.conf
fi

exec syslog-ng -F -p /var/run/syslog-ng.pid $SYSLOGNG_OPTS
